version: '3'

services:
  postgres:
    container_name: pg-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=coderhub
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./data:/data
      - ./create_second_db.sh:/docker-entrypoint-initdb.d/create_second_db.sh
    ports:
      - 5432:5432
